apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - image: yjavvaji/assesment
          imagePullPolicy: Always
          name: website
          ports:
            - containerPort: 80
